model:
  name: "./results/mamba-130m-finetuned"
  new_model: "mamba-130m-charflip"

dataset:
  path: "../data/train/D_ad_cflipped.csv"

training:
  output_dir: "./results"
  num_train_epochs: 10
  per_device_train_batch_size: 2
  per_device_eval_batch_size: 2
  learning_rate: 0.00001
  weight_decay: 0.1
  max_grad_norm: 1.0
  logging_steps: 100
  warmup_steps: 100
